[package]
name = "vector_db"
version = "0.1.0"
edition = "2024"

[dependencies]
parking_lot = "0.12.4"

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "arena_benchmark"
harness = false
path = "benches/arena_benchmark.rs"
